server:
  port: 8090

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO

spring:
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: spring-security-client
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            scope: openid,read:user
        provider:
          keycloak:
            authorization-uri: http://localhost:18080/realms/spring-security-realm/protocol/openid-connect/auth
            token-uri: http://localhost:18080/realms/spring-security-realm/protocol/openid-connect/token
            user-info-uri: http://localhost:18080/realms/spring-security-realm/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:18080/realms/spring-security-realm/protocol/openid-connect/certs
            user-name-attribute: preferred_username
